version: '3'

services:
  web:
    build: .
    command: sh -c "python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    restart: always
    environment:
      - PYTHONUNBUFFERED=0
    ports:
      - 8000:8000
    volumes:
      - ./notifier:/code
    depends_on:
      - db
      - redis

  db:
    image: postgres:10-alpine
    restart: always
    environment:
      - POSTGRES_DB=notifier
    ports:
      - 5433:5432
    volumes:
      - db_vol:/var/lib/postgresql/data/

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A notifier worker -l info -B
    volumes:
      - ./notifier:/code
    depends_on:
      - db
      - redis

  flower:
    image: mher/flower
    command: ["flower", "--broker=redis://redis:6379/0"]
    ports:
      - 8005:5555
    depends_on:
      - redis

volumes:
  db_vol: {}